### ISSUE TITLE
Design Docs

### ISSUE THREAD

**Issue by cbaker-ut** [yongbingao/greens#1]
Hey Ben!
Nice work so far on your Design Docs, just a few notes moving forward.

- [x] At the moment, your markdown files for your MVP list and Schema are part of your directory structure. These should be moved to the 'Wiki' section of your GitHub page and removed from your app. Let me know if you have any questions about this particular step, this should be a decent example https://github.com/appacademy/bluebird/wiki 

- [x] AAonline lists the Dashboard/Portfolio as being the first MVP, I would advise that after completing User Auth you move on to Asset/Stock detail, tackling Dashboard/Portfolio after, as one can't have much of a portfolio without individual stocks. From there, Watchlist and Search will be straightforward to implement.

- [x] Instead of keeping track of all stock data in one Stocks table, it may be more effective to keep track of just the name and ticker symbol in a Companies table, and then the price information in a Transactions table. The responsibilities of this table would be to keep track of the user_id of the buyer, how many shares they bought, the price at the time of sale and the company_id. Other than that, your schema looks good to me.

Let me know if you have any questions!

**Comment by yongbingao** [comment]
Thanks for the feedback. The design docs have been moved to the Wiki section. The MVP list was edited to have the stock details page done before the dashboard. Also, the schema was changed; the stocks table was separated into the following tables:
- companies table (holds the ticker and additional info on the company)
- prices table (holds the company_id and daily prices)  
- transactions table (holds info on each buy/sell ticker and shares)
